Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
 Enabled: false

Naming/MemoizedInstanceVariableName:
 Enabled: false

AllCops:
  TargetRubyVersion: 2.4.1

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'Rakefile'
