before_install:
- gem install bundler

langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mFSApauSbXI+KWP8NXsOYhDGcJ6HquUpODA83F4zLAENqBfHBKYioc7j9Tlrn7d214EUuwr2nXonCaVITmwrngu
ZdBnwPHsf2wdmLhgqcc+HVfk+eEuMJKP77CEazI6zH+BhVFisYSvs7NuSzf8CxTm/QLFj4d8XpwQyyBbSzwl48kUgQz1+kTGYD
U+4UwExhdCVnJZYCLDNkXyLNcLEa7yY44xWAQw+iW8SNv6uSi0LGK/H2z7NXZFWT01DGFZu3c5DfGwYUaZSGUE04sC/o/pOeig
QB+a+FLTlgN7Rb1Rwhf8JAPadsdXotiz/9KXRd1+ERtQN59Sryytk1qWGCXXfOa9pq8nS2lgIoINTr+cvdtLeqRx8APWy7WOO3
TJHOQvAAIzPT9dhLVpWqMOKeIribjcVa3d529xtInEyrayeVoOfnPZ/uoBtq4EUhfdL2wUCV18v/NkliXOUatghUcmwHqxiTRq
NcWvZ4bX6ppXHiuL0QFTx3SW6QSfZ98g3qBQtNlDQEhEniBKfkVRhdbUcyTKhTOqcE23uMuOQcd1iUTKCzY0I2DSXNVNxVI57+
/3mgrPAlkGyB8hs2kyop4OCqObEKMMOMocFO1yJ7csMES1k6kaTKctCNNeaXy27uh88H2tWp3pG60SIs3y8e2ALADAIMjv9N5A
gjR5Tx1I=
  app: gentle-atoll-82746
  run: rails db:migrate


